#!/bin/bash

set -ueC

if [[ $# == 0 || $1 == "-h" || $1 == "--help" ]]; then
    cat <<EOF
Usage: mfasta-idlist.sh FAIDX [ORGANISM]

Output a list of FASTA record ids. If ORGANISM is specified, an additional
column called "organism" is added, with all of its values being ORGANISM.

The file FAIDX can be generated by calling 'samtools faidx' on a FASTA file.

Given a FASTA file named example.fasta:

>A Chromosome A
ATTAGAGACTATACCATAGATGAGAC
TTCGCTACGCACATGATACCAATCTA
...
>B Chromosome B
CCATTTTTTTCCCCCATTTCTACTAC
CTACATACTATTTTTTTCTAAATATC
...
>C Chromosome C
CACAAACACCCCCCCCATCGGGGACT
ACTTAATACTGGGGGATCATCTTTTT
...

for which an index called 'example.fasta.fai' was generated, a call of 

    mfasta-idlist.sh example.fasta.fai dog 
    
yields the tab-separated output:

record  organism
A       dog
B       dog
C       dog

EOF
exit 1
fi

s_index_column="$(dirname "$0")/../general/index-column.py"

function org_column(){
    if [ -z ${1-} ]; then
        # copy stdin to stdout
        cat
    else
        # Read from stdin and add organism column
        awk -vOFS=$'\t' '(NR == 1){print $0, "organism";next}; 
                                  {print $0, "'$1'"}'
    fi
}

# Read from standard input
(echo "record" ; cat "$1") | \
    awk '{print $1}' | \
    org_column "${2-}"


